import "./globals.css";
import { Inter } from "next/font/google";
import NavTop from "@/components/NavTop";
import NavBottom from "@/components/NavBottom";
import { AuthProvider } from "@/lib/(auth)/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`min-h-screen  bg-blur-lg bg-gradient-to-r from-5% from-slate-900 via-black via-50% to-slate-900 to-95% ${inter.className}`}
      >
        <AuthProvider>
          <NavTop />
          <main className="relative m-auto flex w-full flex-col items-center justify-center h-screen pb-16">
            {children}
          </main>
          <NavBottom />
        </AuthProvider>
      </body>
    </html>
  );
}
