import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`min-h-screen bg-blur-lg bg-gradient-to-r from-black from-5% via-slate-900 via-50% to-black to-95% ${inter.className}`}
        >
          <main className="relative m-auto flex w-full flex-col items-center justify-center h-screen">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
